import { buildFrameRows, buildSecurityRows, getConservationState } from '../../engine/journal-view';
import { useAppStore, type JournalGasNode } from '../../engine/store';
import './Flow.css';

function GasNode({ node, depth = 0 }: { node: JournalGasNode; depth?: number }) {
  return <li className={`gas-node effect-${node.effect}`}><div className="gas-node-row" style={{ paddingLeft: `${12 + depth * 18}px` }}><span className="gas-node-mark" /><span className="gas-node-label">{node.label}</span>{node.frameId !== null && <span className="gas-frame">F{node.frameId}</span>}<span className="gas-semantics">{node.semantics}</span><span className="gas-amount">{node.effect === 'credit' ? '−' : node.effect === 'charge' ? '+' : '≈'}{node.amount.toLocaleString()}</span><span className="gas-total">Σ {node.totalGas.toLocaleString()}</span></div>{node.children.length > 0 && <ul>{node.children.map((child) => <GasNode key={child.id} node={child} depth={depth + 1} />)}</ul>}</li>;
}

export function Flow() {
  const result = useAppStore((state) => state.result);
  const setCurrentStep = useAppStore((state) => state.setCurrentStep);
  const setActiveView = useAppStore((state) => state.setActiveView);
  if (!result) return <div className="flow-view flow-empty">Execute a trace to inspect exclusive gas ownership.</div>;
  const conservation = getConservationState(result.conservation);
  const frames = buildFrameRows(result.frameTree);
  const findings = buildSecurityRows(result.frameTree, result.securityFindings);
  return <div className="flow-view"><header className="flow-header"><div><span className="flow-kicker">JOURNAL ACCOUNTING</span><h2>Gas ownership topology</h2></div><div className={`flow-conservation ${conservation.tone}`}><strong>{conservation.label}</strong><span>{result.conservation.derivedGas.toLocaleString()} derived / {result.conservation.settledGas.toLocaleString()} settled</span></div></header><div className="flow-grid"><section className="flow-panel frame-panel"><h3>Frame interferogram</h3><p>Explicit execution ownership. Child opcodes stay in their child frame.</p><div className="frame-list">{frames.map((frame) => <div className="frame-row" key={frame.id} style={{ marginLeft: frame.indent * 18 }} role="button" tabIndex={0} onClick={() => { const index = result.steps.findIndex((step) => step.frameId === frame.id); if (index >= 0) { setCurrentStep(index); setActiveView('workbench'); } }}><span className="frame-pulse" style={{ ['--frame-hue' as string]: `${205 + (frame.id * 47) % 110}` }} /><strong>F{frame.id}</strong><span>{frame.callType}</span><code>{frame.contractAddress}</code><b>{frame.gasUsed?.toLocaleString() ?? '—'} gas</b></div>)}</div></section><section className="flow-panel gas-panel"><h3>Exclusive gas tree</h3><p>Charges add, credits subtract, forwarded gas remains non-additive evidence.</p><ul className="gas-tree"><GasNode node={result.gasTree} /></ul></section><section className="flow-panel security-panel"><h3>Proof-linked security evidence</h3><p>Server-graded findings retain exact frame ancestry, effect disposition, and evidence sequences.</p><div className="security-list">{findings.length === 0 ? <span className="security-empty">No journal-backed patterns on this path.</span> : findings.map((finding) => <article className={`security-finding severity-${finding.severity}`} key={finding.id}><div className="security-title"><strong>{finding.ruleId}</strong><span>{finding.severity} · {finding.factGrade}</span></div><p>{finding.summary}</p><div className="security-proof"><code>{finding.framePath.map((id) => `F${id}`).join(' → ')}</code><span>events {finding.supportingEventSequences.join(', ')}</span><span>{finding.executionDisposition} / {finding.persistenceDisposition}</span></div></article>)}</div></section></div></div>;
}
