using Schlieren.Harvest.Calibration;
using Schlieren.Harvest.Domain;
using Xunit;

namespace Schlieren.Harvest.Tests.Calibration;

/// <summary>
/// CalibrationSuite tests.
///
/// Contracts per Task 7 Step 3 + acceptance points:
///
/// SIX PROBES (hand-authored, expected values are TEST DATA, not generated by comparator):
///   1. ExactMatch      → Pass
///   2. GasMismatch     → Divergence
///   3. StatusMismatch  → Divergence
///   4. StorageMismatch → Divergence
///   5. MalformedFixture → FixtureInvalid or HarnessError
///   6. KilledWorker    → Aborted
///
/// CalibrationSuite.RunAsync returns CalibrationRecord with:
///   - one CalibrationProbeResult per probe
///   - an ApparagusGate (pass only when all 6 classify exactly)
///
/// The expected classification for each probe is declared in test data BEFORE
/// calling the comparator — comparator output is compared against it, not the reverse.
/// </summary>
public class CalibrationSuiteTests
{
    // ── All six probes present ────────────────────────────────────────────

    [Fact]
    public async Task CalibrationSuite_HasSixProbes()
    {
        var record = await CalibrationSuite.RunAsync();

        Assert.Equal(6, record.ProbeResults.Count);
    }

    // ── Probe 1: ExactMatch → Pass ────────────────────────────────────────

    [Fact]
    public async Task Probe_ExactMatch_ClassifiesAsPass()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.ExactMatch);
        Assert.Equal(CaseStatus.Pass, probe.ActualStatus);
        Assert.Equal(CaseStatus.Pass, probe.ExpectedStatus); // hand-authored
        Assert.True(probe.ClassifiedCorrectly);
    }

    // ── Probe 2: GasMismatch → Divergence ────────────────────────────────

    [Fact]
    public async Task Probe_GasMismatch_ClassifiesAsDivergence()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.GasMismatch);
        Assert.Equal(CaseStatus.Divergence, probe.ActualStatus);
        Assert.Equal(CaseStatus.Divergence, probe.ExpectedStatus);
        Assert.True(probe.ClassifiedCorrectly);

        // Must carry a gas delta
        Assert.Contains(probe.Deltas, d => d.Layer == Domain.DiscrepancyLayer.Gas);
    }

    // ── Probe 3: StatusMismatch → Divergence ─────────────────────────────

    [Fact]
    public async Task Probe_StatusMismatch_ClassifiesAsDivergence()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.StatusMismatch);
        Assert.Equal(CaseStatus.Divergence, probe.ActualStatus);
        Assert.True(probe.ClassifiedCorrectly);
        Assert.Contains(probe.Deltas, d => d.Layer == Domain.DiscrepancyLayer.Validity);
    }

    // ── Probe 4: StorageMismatch → Divergence ────────────────────────────

    [Fact]
    public async Task Probe_StorageMismatch_ClassifiesAsDivergence()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.StorageMismatch);
        Assert.Equal(CaseStatus.Divergence, probe.ActualStatus);
        Assert.True(probe.ClassifiedCorrectly);
        Assert.Contains(probe.Deltas, d => d.Layer == Domain.DiscrepancyLayer.Storage);
    }

    // ── Probe 5: MalformedFixture → FixtureInvalid or HarnessError ───────

    [Fact]
    public async Task Probe_MalformedFixture_ClassifiesAsFixtureInvalidOrHarnessError()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.MalformedFixture);
        Assert.True(
            probe.ActualStatus == CaseStatus.FixtureInvalid ||
            probe.ActualStatus == CaseStatus.HarnessError,
            $"Expected FixtureInvalid or HarnessError but got {probe.ActualStatus}");
        Assert.True(probe.ClassifiedCorrectly);
    }

    // ── Probe 6: KilledWorker → Aborted ──────────────────────────────────

    [Fact]
    public async Task Probe_KilledWorker_ClassifiesAsAborted()
    {
        var record = await CalibrationSuite.RunAsync();

        var probe = FindProbe(record, CalibrationProbeKind.KilledWorker);
        Assert.Equal(CaseStatus.Aborted, probe.ActualStatus);
        Assert.Equal(CaseStatus.Aborted, probe.ExpectedStatus);
        Assert.True(probe.ClassifiedCorrectly);
    }

    // ── Apparatus gate: passes only when all 6 are correct ───────────────

    [Fact]
    public async Task ApparatusGate_PassesWhenAllSixCorrect()
    {
        var record = await CalibrationSuite.RunAsync();

        Assert.True(record.ApparatusGatePassed,
            "Apparatus gate must pass when all six probes classify correctly");
    }

    [Fact]
    public async Task ApparatusGate_AllProbesClassifiedCorrectly()
    {
        var record = await CalibrationSuite.RunAsync();

        var incorrect = record.ProbeResults.Where(p => !p.ClassifiedCorrectly).ToList();
        Assert.Empty(incorrect);
    }

    // ── Expected values are test data, not comparator output ─────────────

    [Fact]
    public async Task AllProbes_HaveExplicitExpectedStatus()
    {
        // Every probe must have an ExpectedStatus set in the calibration suite's
        // hand-authored test data — it must NOT be null or unset
        var record = await CalibrationSuite.RunAsync();

        foreach (var probe in record.ProbeResults)
        {
            Assert.True(
                Enum.IsDefined(probe.ExpectedStatus),
                $"Probe {probe.Kind} has an undefined ExpectedStatus — it must be hand-authored");
        }
    }

    // ── Six distinct probe kinds ──────────────────────────────────────────

    [Fact]
    public async Task CalibrationSuite_CoversAllSixDistinctKinds()
    {
        var record = await CalibrationSuite.RunAsync();

        var kinds = record.ProbeResults.Select(p => p.Kind).ToHashSet();
        Assert.Contains(CalibrationProbeKind.ExactMatch,      kinds);
        Assert.Contains(CalibrationProbeKind.GasMismatch,     kinds);
        Assert.Contains(CalibrationProbeKind.StatusMismatch,  kinds);
        Assert.Contains(CalibrationProbeKind.StorageMismatch, kinds);
        Assert.Contains(CalibrationProbeKind.MalformedFixture, kinds);
        Assert.Contains(CalibrationProbeKind.KilledWorker,    kinds);
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private static CalibrationProbeResult FindProbe(CalibrationRecord record, CalibrationProbeKind kind)
    {
        var probe = record.ProbeResults.FirstOrDefault(p => p.Kind == kind);
        Assert.NotNull(probe);
        return probe!;
    }
}
