; This file describes fixture build properties

[fixtures]
timestamp = 2026-07-15T00:00:00.000000
build = stable
ref = refs/tags/tests@v20.0.1
release = tests@v20.0.1
source_repo = https://github.com/ethereum/execution-specs
download_url = https://github.com/ethereum/execution-specs/releases/download/tests%40v20.0.1/fixtures.tar.gz
local_path = fixtures/fixtures/
forks = Osaka,Prague,Cancun,Shanghai,Paris,London,Berlin,Istanbul,ConstantinopleFix,Homestead,Frontier,Byzantium,SpuriousDragon,TangerineWhistle

[packages]
pytest = 8.4.2
pluggy = 1.6.0

[plugins]
json-report = 1.5.0
xdist = 3.8.0
cov = 4.1.0
html = 4.1.1
custom-report = 1.0.1
regex = 0.2.0
metadata = 3.1.1

[tools]
t8n = 2.18.0rc6

[environment]
python = 3.12.3
platform = Linux-6.8.0-87-generic-x86_64-with-glibc2.39
ci = true

