namespace Scrutor.UI.Branding;

/// <summary>
/// Curated skins — long sessions, brand boards, Sounder, and ethereum-dev culture.
/// </summary>
public static class SkinCatalog
{
    public const string DefaultSkinId = "arctic-night";

    public static IReadOnlyList<UiSkin> All { get; } =
    [
        // ── Comfort / work ───────────────────────────────────────────────
        new UiSkin(
            Id: "arctic-night",
            DisplayName: "Arctic Night",
            Description: "Nord blue-grey. Lowest eye strain for long conformance runs.",
            Category: "Comfort",
            ShellBg: "#0B0E14", PanelDeep: "#0D1117", PanelBg: "#151B23", PanelElevated: "#1C2430",
            Border: "#2A3441", BorderSubtle: "#232B36",
            TextPrimary: "#E6EDF3", TextMuted: "#9AA7B5", TextDim: "#6B7785",
            Accent: "#6C9EFF", AccentAlt: "#7FDBCA", AccentHover: "#8FB4FF", AccentSoft: "#A8B4FF",
            Success: "#3DDC97", Danger: "#FF6B7A", Warning: "#E6C07B", Alert: "#FF8A65",
            ActiveLineBg: "#1A2740", VulnerableLineBg: "#2A1818", SelectionBg: "#243044",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 0.85),

        new UiSkin(
            Id: "midnight-soft",
            DisplayName: "Midnight Soft",
            Description: "Brand DNA, desaturated. Indigo/aqua without the headache.",
            Category: "Comfort",
            ShellBg: "#0C0E16", PanelDeep: "#10131C", PanelBg: "#171B28", PanelElevated: "#1E2333",
            Border: "#2C3348", BorderSubtle: "#252A3A",
            TextPrimary: "#E8ECF4", TextMuted: "#9BA3B5", TextDim: "#6E768A",
            Accent: "#6B5CFF", AccentAlt: "#4ECFDC", AccentHover: "#8478FF", AccentSoft: "#A89BFF",
            Success: "#3ECF8E", Danger: "#F07178", Warning: "#E6B450", Alert: "#FF7B54",
            ActiveLineBg: "#1E2240", VulnerableLineBg: "#2A1A1E", SelectionBg: "#222840",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 0.9),

        new UiSkin(
            Id: "obsidian-amber",
            DisplayName: "Obsidian Amber",
            Description: "Warm charcoal + amber. Feels expensive at 2am.",
            Category: "Comfort",
            ShellBg: "#0E0C0A", PanelDeep: "#12100E", PanelBg: "#1A1714", PanelElevated: "#221E1A",
            Border: "#3A342C", BorderSubtle: "#2E2923",
            TextPrimary: "#F2EDE6", TextMuted: "#B0A697", TextDim: "#7A7268",
            Accent: "#E8A54B", AccentAlt: "#D4A574", AccentHover: "#F0B86A", AccentSoft: "#C9A87C",
            Success: "#8FBF6A", Danger: "#E07060", Warning: "#E8C060", Alert: "#E08050",
            ActiveLineBg: "#2A2218", VulnerableLineBg: "#2A1814", SelectionBg: "#2C241C",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 0.8),

        // ── Scrutor brand ────────────────────────────────────────────────
        new UiSkin(
            Id: "brand-classic",
            DisplayName: "Brand Classic",
            Description: "Official Scrutor board: Execution Indigo + Blob Aqua. Demo screenshots.",
            Category: "Brand",
            ShellBg: "#0D0D0D", PanelDeep: "#0C0D14", PanelBg: "#1A1A2E", PanelElevated: "#1E1E2E",
            Border: "#2D2D2D", BorderSubtle: "#2D2D3D",
            TextPrimary: "#F0F4F8", TextMuted: "#A9A9A9", TextDim: "#888888",
            Accent: "#4A00E0", AccentAlt: "#19D7E5", AccentHover: "#5B14F0", AccentSoft: "#B794F6",
            Success: "#22C55E", Danger: "#EF4444", Warning: "#FFD700", Alert: "#FF4500",
            ActiveLineBg: "#241B47", VulnerableLineBg: "#2E141B", SelectionBg: "#1A1040",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 1.15),

        // ── Sounder Solutions ────────────────────────────────────────────
        // Accent #FF6A00 from pitch tooling; navy #003366 / #002244 from site CSS
        new UiSkin(
            Id: "sounder-field",
            DisplayName: "Sounder Field Ops",
            Description: "Sounder Solutions: blaze orange + deep navy. Field-ops command center.",
            Category: "Sounder",
            ShellBg: "#061018",
            PanelDeep: "#0A1520",
            PanelBg: "#0F1F30",
            PanelElevated: "#152A40",
            Border: "#1E3A55",
            BorderSubtle: "#18324A",
            TextPrimary: "#F4F7FA",
            TextMuted: "#9BB0C4",
            TextDim: "#6A8299",
            Accent: "#FF6A00",
            AccentAlt: "#FFB347",
            AccentHover: "#FF8533",
            AccentSoft: "#FF9A4D",
            Success: "#3DDC97",
            Danger: "#FF5A5A",
            Warning: "#FFB020",
            Alert: "#FF6A00",
            ActiveLineBg: "#1A3048",
            VulnerableLineBg: "#2A1810",
            SelectionBg: "#1C3348",
            ArtMotif: SkinArtMotif.SounderSigil, WatermarkBoost: 1.25),

        new UiSkin(
            Id: "sounder-dusk",
            DisplayName: "Sounder Dusk",
            Description: "Softer Sounder — orange accents on charcoal field grey. Easier nights.",
            Category: "Sounder",
            ShellBg: "#0C0D0E",
            PanelDeep: "#121416",
            PanelBg: "#1A1D20",
            PanelElevated: "#23272B",
            Border: "#3A4048",
            BorderSubtle: "#2C3138",
            TextPrimary: "#F0F2F4",
            TextMuted: "#A8AEB6",
            TextDim: "#737A84",
            Accent: "#E85D04",
            AccentAlt: "#F48C06",
            AccentHover: "#F48C06",
            AccentSoft: "#FAA307",
            Success: "#52B788",
            Danger: "#E76F51",
            Warning: "#F4A261",
            Alert: "#E85D04",
            ActiveLineBg: "#2A2418",
            VulnerableLineBg: "#2A1814",
            SelectionBg: "#2A2218",
            ArtMotif: SkinArtMotif.SounderSigil, WatermarkBoost: 1.05),

        // ── Ethereum / dev-geek culture ──────────────────────────────────
        // What eth devs actually live in: Tokyo Night, Catppuccin, Dracula, ETH purple, Foundry
        new UiSkin(
            Id: "eth-violet",
            DisplayName: "Ethereum Violet",
            Description: "ETH logo energy — violet #627EEA on deep void. Conference-floor classic.",
            Category: "Ethereum Dev",
            ShellBg: "#0A0B12",
            PanelDeep: "#0E1018",
            PanelBg: "#141625",
            PanelElevated: "#1C1F33",
            Border: "#2E3350",
            BorderSubtle: "#242840",
            TextPrimary: "#EEF0F8",
            TextMuted: "#A0A6C0",
            TextDim: "#6E7494",
            Accent: "#627EEA",
            AccentAlt: "#8BA4FF",
            AccentHover: "#7B91F0",
            AccentSoft: "#A8B8FF",
            Success: "#3DDC97",
            Danger: "#FF6B81",
            Warning: "#F0C674",
            Alert: "#FF8E53",
            ActiveLineBg: "#1A1E38",
            VulnerableLineBg: "#2A1520",
            SelectionBg: "#1E2240",
            ArtMotif: SkinArtMotif.EthDiamond, WatermarkBoost: 1.35),

        new UiSkin(
            Id: "tokyo-night",
            DisplayName: "Tokyo Night",
            Description: "The VS Code / Neovim default of a generation. Clean blue-violet grit.",
            Category: "Ethereum Dev",
            ShellBg: "#1A1B26",
            PanelDeep: "#16161E",
            PanelBg: "#1F2335",
            PanelElevated: "#24283B",
            Border: "#3B4261",
            BorderSubtle: "#292E42",
            TextPrimary: "#C0CAF5",
            TextMuted: "#A9B1D6",
            TextDim: "#565F89",
            Accent: "#7AA2F7",
            AccentAlt: "#7DCFFF",
            AccentHover: "#89B4FA",
            AccentSoft: "#BB9AF7",
            Success: "#9ECE6A",
            Danger: "#F7768E",
            Warning: "#E0AF68",
            Alert: "#FF9E64",
            ActiveLineBg: "#292E42",
            VulnerableLineBg: "#2A1A22",
            SelectionBg: "#2A2F45",
            ArtMotif: SkinArtMotif.EthDiamond, WatermarkBoost: 0.95),

        new UiSkin(
            Id: "catppuccin-mocha",
            DisplayName: "Catppuccin Mocha",
            Description: "Soothing pastel-on-mocha. The coziest stack-trace skin in web3 Discord.",
            Category: "Ethereum Dev",
            ShellBg: "#11111B",
            PanelDeep: "#181825",
            PanelBg: "#1E1E2E",
            PanelElevated: "#313244",
            Border: "#45475A",
            BorderSubtle: "#313244",
            TextPrimary: "#CDD6F4",
            TextMuted: "#A6ADC8",
            TextDim: "#6C7086",
            Accent: "#CBA6F7",
            AccentAlt: "#89B4FA",
            AccentHover: "#F5C2E7",
            AccentSoft: "#B4BEFE",
            Success: "#A6E3A1",
            Danger: "#F38BA8",
            Warning: "#F9E2AF",
            Alert: "#FAB387",
            ActiveLineBg: "#313244",
            VulnerableLineBg: "#2A1A22",
            SelectionBg: "#313244",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 0.9),

        new UiSkin(
            Id: "dracula",
            DisplayName: "Dracula",
            Description: "Purple blood on charcoal. Classic hacker cosplay that still reads well.",
            Category: "Ethereum Dev",
            ShellBg: "#191A21",
            PanelDeep: "#21222C",
            PanelBg: "#282A36",
            PanelElevated: "#343746",
            Border: "#44475A",
            BorderSubtle: "#383A4A",
            TextPrimary: "#F8F8F2",
            TextMuted: "#BFBFB8",
            TextDim: "#6272A4",
            Accent: "#BD93F9",
            AccentAlt: "#8BE9FD",
            AccentHover: "#FF79C6",
            AccentSoft: "#D6ACFF",
            Success: "#50FA7B",
            Danger: "#FF5555",
            Warning: "#F1FA8C",
            Alert: "#FFB86C",
            ActiveLineBg: "#343746",
            VulnerableLineBg: "#3A2028",
            SelectionBg: "#44475A",
            ArtMotif: SkinArtMotif.VoidSigil, WatermarkBoost: 1.1),

        new UiSkin(
            Id: "foundry-anvil",
            DisplayName: "Foundry Anvil",
            Description: "Rust-forge heat — charcoal + copper. For people who live in forge test -vvv.",
            Category: "Ethereum Dev",
            ShellBg: "#0D0B0A",
            PanelDeep: "#141210",
            PanelBg: "#1C1917",
            PanelElevated: "#292524",
            Border: "#44403C",
            BorderSubtle: "#33302C",
            TextPrimary: "#F5F5F4",
            TextMuted: "#A8A29E",
            TextDim: "#78716C",
            Accent: "#F97316",
            AccentAlt: "#FDBA74",
            AccentHover: "#FB923C",
            AccentSoft: "#FDBA74",
            Success: "#4ADE80",
            Danger: "#F87171",
            Warning: "#FBBF24",
            Alert: "#FB923C",
            ActiveLineBg: "#2A2018",
            VulnerableLineBg: "#2A1414",
            SelectionBg: "#2C2218",
            ArtMotif: SkinArtMotif.VoidSigil, WatermarkBoost: 1.0),

        new UiSkin(
            Id: "phosphor",
            DisplayName: "Phosphor",
            Description: "Muted matrix green. Audit-terminal vibes without laser retina burn.",
            Category: "Ethereum Dev",
            ShellBg: "#080B09", PanelDeep: "#0A0F0C", PanelBg: "#101814", PanelElevated: "#16201A",
            Border: "#24332A", BorderSubtle: "#1C2820",
            TextPrimary: "#D6E8DC", TextMuted: "#8FAE9A", TextDim: "#5F7A68",
            Accent: "#3DDC84", AccentAlt: "#6EE7B7", AccentHover: "#55E898", AccentSoft: "#7DCEA0",
            Success: "#4ADE80", Danger: "#F87171", Warning: "#FBBF24", Alert: "#FB923C",
            ActiveLineBg: "#14241A", VulnerableLineBg: "#241414", SelectionBg: "#1A2C22",
            ArtMotif: SkinArtMotif.ScrutorMark, WatermarkBoost: 1.0),

        new UiSkin(
            Id: "void-crystal",
            DisplayName: "Void Crystal",
            Description: "Badass cyber — magenta/cyan on pure void. Screenshot bait for X.",
            Category: "Ethereum Dev",
            ShellBg: "#050508",
            PanelDeep: "#0A0A10",
            PanelBg: "#10101A",
            PanelElevated: "#181828",
            Border: "#2A2A48",
            BorderSubtle: "#1E1E35",
            TextPrimary: "#F0F0FF",
            TextMuted: "#A0A0C8",
            TextDim: "#6868A0",
            Accent: "#FF2D95",
            AccentAlt: "#00F0FF",
            AccentHover: "#FF5CAD",
            AccentSoft: "#C77DFF",
            Success: "#39FF14",
            Danger: "#FF1744",
            Warning: "#FFE600",
            Alert: "#FF6D00",
            ActiveLineBg: "#1A1030",
            VulnerableLineBg: "#2A0A18",
            SelectionBg: "#1A1435",
            ArtMotif: SkinArtMotif.VoidSigil, WatermarkBoost: 1.4),

        new UiSkin(
            Id: "high-contrast",
            DisplayName: "High Contrast",
            Description: "Max contrast for projectors and accessibility demos.",
            Category: "Utility",
            ShellBg: "#000000", PanelDeep: "#0A0A0A", PanelBg: "#121212", PanelElevated: "#1A1A1A",
            Border: "#555555", BorderSubtle: "#444444",
            TextPrimary: "#FFFFFF", TextMuted: "#CCCCCC", TextDim: "#999999",
            Accent: "#00B7FF", AccentAlt: "#00FFD0", AccentHover: "#33C5FF", AccentSoft: "#80D4FF",
            Success: "#00FF88", Danger: "#FF3355", Warning: "#FFDD00", Alert: "#FF6600",
            ActiveLineBg: "#003355", VulnerableLineBg: "#330000", SelectionBg: "#002244",
            ArtMotif: SkinArtMotif.None, WatermarkBoost: 0.5),
    ];

    public static IEnumerable<IGrouping<string, UiSkin>> ByCategory() =>
        All.GroupBy(s => s.Category);

    public static UiSkin Get(string? id) =>
        All.FirstOrDefault(s => string.Equals(s.Id, id, StringComparison.OrdinalIgnoreCase))
        ?? All.First(s => s.Id == DefaultSkinId);
}
