#!/usr/bin/env python3
"""
Stages a real, deployed mainnet contract into muscle/inbound/ for later use as a
Schlieren regression test (real compiler-generated bytecode has patterns — ABI
dispatch, free-memory-pointer layout, revert encoding, packed storage — that
hand-written test bytecode doesn't reproduce).

Usage:
    python import_real_contract.py <address> <name> [--rpc URL] [--note TEXT]

Writes:
    muscle/inbound/<name>/runtime.hex   — deployed runtime bytecode
    muscle/inbound/<name>/meta.json     — address, fetch block, byte length, note
    muscle/inbound/manifest.json        — updated index (status: "staged")

Next step for a staged contract: pick a real selector/call, seed a
Schlieren.Tests/Regression/RealWorldContractTests.cs case (or run it through
import_real_tx.py against an actual mainnet transaction hash for that address to
get a real receipt as ground truth), then flip its manifest status to "promoted".
"""
import argparse
import json
import sys
import urllib.request
from pathlib import Path
from datetime import datetime, timezone

DEFAULT_RPC = "https://ethereum.publicnode.com"
REPO_ROOT = Path(__file__).parent.parent
INBOUND_DIR = REPO_ROOT / "muscle" / "inbound"
MANIFEST_PATH = INBOUND_DIR / "manifest.json"


def rpc_call(rpc_url, method, params):
    body = json.dumps({"jsonrpc": "2.0", "method": method, "params": params, "id": 1}).encode()
    headers = {"Content-Type": "application/json", "User-Agent": "curl/8.0"}
    req = urllib.request.Request(rpc_url, data=body, headers=headers)
    with urllib.request.urlopen(req, timeout=20) as resp:
        payload = json.loads(resp.read())
    if "error" in payload:
        raise RuntimeError(f"{method} failed: {payload['error']}")
    return payload["result"]


def load_manifest():
    if MANIFEST_PATH.exists():
        return json.loads(MANIFEST_PATH.read_text())
    return {"contracts": []}


def save_manifest(manifest):
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")


def stage_contract(address, name, rpc_url, note):
    latest = rpc_call(rpc_url, "eth_blockNumber", [])
    code = rpc_call(rpc_url, "eth_getCode", [address, latest])
    if code in (None, "0x"):
        raise RuntimeError(f"{address} has no code at block {latest} — not a contract, or wrong address")

    contract_dir = INBOUND_DIR / name
    contract_dir.mkdir(parents=True, exist_ok=True)
    (contract_dir / "runtime.hex").write_text(code)

    byte_len = (len(code) - 2) // 2
    meta = {
        "name": name,
        "address": address,
        "network": "mainnet",
        "fetchedAtBlock": latest,
        "fetchedAtUtc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "runtimeBytes": byte_len,
        "note": note or "",
    }
    (contract_dir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")

    manifest = load_manifest()
    manifest["contracts"] = [c for c in manifest["contracts"] if c["name"] != name]
    manifest["contracts"].append({
        "name": name,
        "address": address,
        "status": "staged",
        "runtimeBytes": byte_len,
        "fetchedAtBlock": latest,
    })
    manifest["contracts"].sort(key=lambda c: c["name"])
    save_manifest(manifest)

    print(f"staged {name} ({address}) — {byte_len} bytes runtime, block {latest}")
    print(f"  -> {contract_dir / 'runtime.hex'}")
    print(f"  -> {contract_dir / 'meta.json'}")
    print(f"  -> {MANIFEST_PATH} updated")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("address")
    p.add_argument("name", help="short identifier, becomes the muscle/inbound/<name>/ directory")
    p.add_argument("--rpc", default=DEFAULT_RPC)
    p.add_argument("--note", default="")
    args = p.parse_args()
    stage_contract(args.address, args.name, args.rpc, args.note)


if __name__ == "__main__":
    sys.exit(main())
